// pages/_app.tsx
import { AppProps } from "next/app";
import Head from "next/head";
import "../src/app/globals.css";
import Navbar from "../src/app/components/Navbar";
import Footer from "../src/app/components/Footer";

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <link
          rel="icon"
          href="/faviconNew.ico"
          type="image/x-icon"
          sizes="16x16"
        />
        <title>OIS Europe</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
};

export default MyApp;
